# Generated by Django 4.2 on 2023-04-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable_diffusion_webui', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='image',
            field=models.FilePathField(),
        ),
    ]
