# Generated by Django 4.2 on 2023-04-06 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stable_diffusion_webui', '0002_alter_prompt_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_body', models.JSONField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='prompt',
            name='request',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stable_diffusion_webui.generaterequest'),
            preserve_default=False,
        ),
    ]
