# Generated by Django 4.2 on 2023-04-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable_diffusion_webui', '0003_generaterequest_prompt_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaterequest',
            name='combinations',
            field=models.JSONField(default="[]"),
            preserve_default=False,
        ),
    ]
