# Generated by Django 4.2 on 2023-04-14 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable_diffusion_webui', '0004_generaterequest_combinations'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptWordStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=128)),
                ('hit', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='prompt',
            name='artistes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prompt',
            name='colors',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prompt',
            name='lightings',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prompt',
            name='mediums',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prompt',
            name='resolutions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prompt',
            name='styles',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prompt',
            name='websites',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
