# Generated by Django 4.2 on 2023-04-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stable_diffusion_webui', '0006_alter_promptwordstat_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptwordstat',
            name='ratio',
            field=models.FloatField(default=0.0),
        ),
    ]
